
/*
 *	MCreator note: This file will be REGENERATED on each build.
 */
package net.lite.allinone.init;

import net.minecraft.world.level.block.Block;
import net.minecraft.resources.ResourceLocation;
import net.minecraft.core.registries.BuiltInRegistries;
import net.minecraft.core.Registry;

import net.lite.allinone.block.TinOreBlock;
import net.lite.allinone.block.TinBlockBlock;
import net.lite.allinone.block.StoneT5Block;
import net.lite.allinone.block.StoneT4Block;
import net.lite.allinone.block.StoneT3Block;
import net.lite.allinone.block.StoneT2Block;
import net.lite.allinone.block.StoneT1Block;
import net.lite.allinone.block.SteelBlockBlock;
import net.lite.allinone.block.SilverOreBlock;
import net.lite.allinone.block.SilverBlockBlock;
import net.lite.allinone.block.SandT5Block;
import net.lite.allinone.block.SandT4Block;
import net.lite.allinone.block.SandT3Block;
import net.lite.allinone.block.SandT2Block;
import net.lite.allinone.block.SandT1Block;
import net.lite.allinone.block.NetherrackT5Block;
import net.lite.allinone.block.NetherrackT4Block;
import net.lite.allinone.block.NetherrackT3Block;
import net.lite.allinone.block.NetherrackT2Block;
import net.lite.allinone.block.NetherrackT1Block;
import net.lite.allinone.block.MarblePillarBlock;
import net.lite.allinone.block.MarbleBricksBlock;
import net.lite.allinone.block.MarbleBlock;
import net.lite.allinone.block.LauncherMk3Block;
import net.lite.allinone.block.LauncherMk2Block;
import net.lite.allinone.block.LauncherMk1Block;
import net.lite.allinone.block.GravelT5Block;
import net.lite.allinone.block.GravelT4Block;
import net.lite.allinone.block.GravelT3Block;
import net.lite.allinone.block.GravelT2Block;
import net.lite.allinone.block.GravelT1Block;
import net.lite.allinone.block.GlowBallBlockBlock;
import net.lite.allinone.block.ExperienceAltarBlock;
import net.lite.allinone.block.EndstoneT5Block;
import net.lite.allinone.block.EndstoneT4Block;
import net.lite.allinone.block.EndstoneT3Block;
import net.lite.allinone.block.EndstoneT2Block;
import net.lite.allinone.block.EndstoneT1Block;
import net.lite.allinone.block.DirtT5Block;
import net.lite.allinone.block.DirtT4Block;
import net.lite.allinone.block.DirtT3Block;
import net.lite.allinone.block.DirtT2Block;
import net.lite.allinone.block.DirtT1Block;
import net.lite.allinone.block.CompressedObsidianT5Block;
import net.lite.allinone.block.CompressedObsidianT4Block;
import net.lite.allinone.block.CompressedObsidianT3Block;
import net.lite.allinone.block.CompressedObsidianT2Block;
import net.lite.allinone.block.CompressedObsidianT1Block;
import net.lite.allinone.block.CobbleT5Block;
import net.lite.allinone.block.CobbleT4Block;
import net.lite.allinone.block.CobbleT3Block;
import net.lite.allinone.block.CobbleT2Block;
import net.lite.allinone.block.CobbleT1Block;
import net.lite.allinone.block.CobbleGenMk1Block;
import net.lite.allinone.block.CoalT5Block;
import net.lite.allinone.block.CoalT4Block;
import net.lite.allinone.block.CoalT3Block;
import net.lite.allinone.block.CoalT2Block;
import net.lite.allinone.block.CoalT1Block;
import net.lite.allinone.block.ClayT5Block;
import net.lite.allinone.block.ClayT4Block;
import net.lite.allinone.block.ClayT3Block;
import net.lite.allinone.block.ClayT2Block;
import net.lite.allinone.block.ClayT1Block;
import net.lite.allinone.block.BasicLampBlock;
import net.lite.allinone.AioMod;

public class AioModBlocks {
	public static Block TIN_ORE;
	public static Block SILVER_ORE;
	public static Block TIN_BLOCK;
	public static Block SILVER_BLOCK;
	public static Block STEEL_BLOCK;
	public static Block GLOW_BALL_BLOCK;
	public static Block MARBLE;
	public static Block MARBLE_BRICKS;
	public static Block MARBLE_PILLAR;
	public static Block COBBLE_T_1;
	public static Block COBBLE_T_2;
	public static Block COBBLE_T_3;
	public static Block COBBLE_T_4;
	public static Block COBBLE_T_5;
	public static Block STONE_T_1;
	public static Block STONE_T_2;
	public static Block STONE_T_3;
	public static Block STONE_T_4;
	public static Block STONE_T_5;
	public static Block GRAVEL_T_1;
	public static Block GRAVEL_T_2;
	public static Block GRAVEL_T_3;
	public static Block GRAVEL_T_4;
	public static Block GRAVEL_T_5;
	public static Block DIRT_T_1;
	public static Block DIRT_T_2;
	public static Block DIRT_T_3;
	public static Block DIRT_T_4;
	public static Block DIRT_T_5;
	public static Block SAND_T_1;
	public static Block SAND_T_2;
	public static Block SAND_T_3;
	public static Block SAND_T_4;
	public static Block SAND_T_5;
	public static Block CLAY_T_1;
	public static Block CLAY_T_2;
	public static Block CLAY_T_3;
	public static Block CLAY_T_4;
	public static Block CLAY_T_5;
	public static Block COAL_T_1;
	public static Block COAL_T_2;
	public static Block COAL_T_3;
	public static Block COAL_T_4;
	public static Block COAL_T_5;
	public static Block COMPRESSED_OBSIDIAN_T_1;
	public static Block COMPRESSED_OBSIDIAN_T_2;
	public static Block COMPRESSED_OBSIDIAN_T_3;
	public static Block COMPRESSED_OBSIDIAN_T_4;
	public static Block COMPRESSED_OBSIDIAN_T_5;
	public static Block NETHERRACK_T_1;
	public static Block NETHERRACK_T_2;
	public static Block NETHERRACK_T_3;
	public static Block NETHERRACK_T_4;
	public static Block NETHERRACK_T_5;
	public static Block ENDSTONE_T_1;
	public static Block ENDSTONE_T_2;
	public static Block ENDSTONE_T_3;
	public static Block ENDSTONE_T_4;
	public static Block ENDSTONE_T_5;
	public static Block BASIC_LAMP;
	public static Block LAUNCHER_MK_2;
	public static Block LAUNCHER_MK_3;
	public static Block LAUNCHER_MK_1;
	public static Block EXPERIENCE_ALTAR;
	public static Block COBBLE_GEN_MK_1;

	public static void load() {
		TIN_ORE = Registry.register(BuiltInRegistries.BLOCK, new ResourceLocation(AioMod.MODID, "tin_ore"), new TinOreBlock());
		SILVER_ORE = Registry.register(BuiltInRegistries.BLOCK, new ResourceLocation(AioMod.MODID, "silver_ore"), new SilverOreBlock());
		TIN_BLOCK = Registry.register(BuiltInRegistries.BLOCK, new ResourceLocation(AioMod.MODID, "tin_block"), new TinBlockBlock());
		SILVER_BLOCK = Registry.register(BuiltInRegistries.BLOCK, new ResourceLocation(AioMod.MODID, "silver_block"), new SilverBlockBlock());
		STEEL_BLOCK = Registry.register(BuiltInRegistries.BLOCK, new ResourceLocation(AioMod.MODID, "steel_block"), new SteelBlockBlock());
		GLOW_BALL_BLOCK = Registry.register(BuiltInRegistries.BLOCK, new ResourceLocation(AioMod.MODID, "glow_ball_block"), new GlowBallBlockBlock());
		MARBLE = Registry.register(BuiltInRegistries.BLOCK, new ResourceLocation(AioMod.MODID, "marble"), new MarbleBlock());
		MARBLE_BRICKS = Registry.register(BuiltInRegistries.BLOCK, new ResourceLocation(AioMod.MODID, "marble_bricks"), new MarbleBricksBlock());
		MARBLE_PILLAR = Registry.register(BuiltInRegistries.BLOCK, new ResourceLocation(AioMod.MODID, "marble_pillar"), new MarblePillarBlock());
		COBBLE_T_1 = Registry.register(BuiltInRegistries.BLOCK, new ResourceLocation(AioMod.MODID, "cobble_t_1"), new CobbleT1Block());
		COBBLE_T_2 = Registry.register(BuiltInRegistries.BLOCK, new ResourceLocation(AioMod.MODID, "cobble_t_2"), new CobbleT2Block());
		COBBLE_T_3 = Registry.register(BuiltInRegistries.BLOCK, new ResourceLocation(AioMod.MODID, "cobble_t_3"), new CobbleT3Block());
		COBBLE_T_4 = Registry.register(BuiltInRegistries.BLOCK, new ResourceLocation(AioMod.MODID, "cobble_t_4"), new CobbleT4Block());
		COBBLE_T_5 = Registry.register(BuiltInRegistries.BLOCK, new ResourceLocation(AioMod.MODID, "cobble_t_5"), new CobbleT5Block());
		STONE_T_1 = Registry.register(BuiltInRegistries.BLOCK, new ResourceLocation(AioMod.MODID, "stone_t_1"), new StoneT1Block());
		STONE_T_2 = Registry.register(BuiltInRegistries.BLOCK, new ResourceLocation(AioMod.MODID, "stone_t_2"), new StoneT2Block());
		STONE_T_3 = Registry.register(BuiltInRegistries.BLOCK, new ResourceLocation(AioMod.MODID, "stone_t_3"), new StoneT3Block());
		STONE_T_4 = Registry.register(BuiltInRegistries.BLOCK, new ResourceLocation(AioMod.MODID, "stone_t_4"), new StoneT4Block());
		STONE_T_5 = Registry.register(BuiltInRegistries.BLOCK, new ResourceLocation(AioMod.MODID, "stone_t_5"), new StoneT5Block());
		GRAVEL_T_1 = Registry.register(BuiltInRegistries.BLOCK, new ResourceLocation(AioMod.MODID, "gravel_t_1"), new GravelT1Block());
		GRAVEL_T_2 = Registry.register(BuiltInRegistries.BLOCK, new ResourceLocation(AioMod.MODID, "gravel_t_2"), new GravelT2Block());
		GRAVEL_T_3 = Registry.register(BuiltInRegistries.BLOCK, new ResourceLocation(AioMod.MODID, "gravel_t_3"), new GravelT3Block());
		GRAVEL_T_4 = Registry.register(BuiltInRegistries.BLOCK, new ResourceLocation(AioMod.MODID, "gravel_t_4"), new GravelT4Block());
		GRAVEL_T_5 = Registry.register(BuiltInRegistries.BLOCK, new ResourceLocation(AioMod.MODID, "gravel_t_5"), new GravelT5Block());
		DIRT_T_1 = Registry.register(BuiltInRegistries.BLOCK, new ResourceLocation(AioMod.MODID, "dirt_t_1"), new DirtT1Block());
		DIRT_T_2 = Registry.register(BuiltInRegistries.BLOCK, new ResourceLocation(AioMod.MODID, "dirt_t_2"), new DirtT2Block());
		DIRT_T_3 = Registry.register(BuiltInRegistries.BLOCK, new ResourceLocation(AioMod.MODID, "dirt_t_3"), new DirtT3Block());
		DIRT_T_4 = Registry.register(BuiltInRegistries.BLOCK, new ResourceLocation(AioMod.MODID, "dirt_t_4"), new DirtT4Block());
		DIRT_T_5 = Registry.register(BuiltInRegistries.BLOCK, new ResourceLocation(AioMod.MODID, "dirt_t_5"), new DirtT5Block());
		SAND_T_1 = Registry.register(BuiltInRegistries.BLOCK, new ResourceLocation(AioMod.MODID, "sand_t_1"), new SandT1Block());
		SAND_T_2 = Registry.register(BuiltInRegistries.BLOCK, new ResourceLocation(AioMod.MODID, "sand_t_2"), new SandT2Block());
		SAND_T_3 = Registry.register(BuiltInRegistries.BLOCK, new ResourceLocation(AioMod.MODID, "sand_t_3"), new SandT3Block());
		SAND_T_4 = Registry.register(BuiltInRegistries.BLOCK, new ResourceLocation(AioMod.MODID, "sand_t_4"), new SandT4Block());
		SAND_T_5 = Registry.register(BuiltInRegistries.BLOCK, new ResourceLocation(AioMod.MODID, "sand_t_5"), new SandT5Block());
		CLAY_T_1 = Registry.register(BuiltInRegistries.BLOCK, new ResourceLocation(AioMod.MODID, "clay_t_1"), new ClayT1Block());
		CLAY_T_2 = Registry.register(BuiltInRegistries.BLOCK, new ResourceLocation(AioMod.MODID, "clay_t_2"), new ClayT2Block());
		CLAY_T_3 = Registry.register(BuiltInRegistries.BLOCK, new ResourceLocation(AioMod.MODID, "clay_t_3"), new ClayT3Block());
		CLAY_T_4 = Registry.register(BuiltInRegistries.BLOCK, new ResourceLocation(AioMod.MODID, "clay_t_4"), new ClayT4Block());
		CLAY_T_5 = Registry.register(BuiltInRegistries.BLOCK, new ResourceLocation(AioMod.MODID, "clay_t_5"), new ClayT5Block());
		COAL_T_1 = Registry.register(BuiltInRegistries.BLOCK, new ResourceLocation(AioMod.MODID, "coal_t_1"), new CoalT1Block());
		COAL_T_2 = Registry.register(BuiltInRegistries.BLOCK, new ResourceLocation(AioMod.MODID, "coal_t_2"), new CoalT2Block());
		COAL_T_3 = Registry.register(BuiltInRegistries.BLOCK, new ResourceLocation(AioMod.MODID, "coal_t_3"), new CoalT3Block());
		COAL_T_4 = Registry.register(BuiltInRegistries.BLOCK, new ResourceLocation(AioMod.MODID, "coal_t_4"), new CoalT4Block());
		COAL_T_5 = Registry.register(BuiltInRegistries.BLOCK, new ResourceLocation(AioMod.MODID, "coal_t_5"), new CoalT5Block());
		COMPRESSED_OBSIDIAN_T_1 = Registry.register(BuiltInRegistries.BLOCK, new ResourceLocation(AioMod.MODID, "compressed_obsidian_t_1"), new CompressedObsidianT1Block());
		COMPRESSED_OBSIDIAN_T_2 = Registry.register(BuiltInRegistries.BLOCK, new ResourceLocation(AioMod.MODID, "compressed_obsidian_t_2"), new CompressedObsidianT2Block());
		COMPRESSED_OBSIDIAN_T_3 = Registry.register(BuiltInRegistries.BLOCK, new ResourceLocation(AioMod.MODID, "compressed_obsidian_t_3"), new CompressedObsidianT3Block());
		COMPRESSED_OBSIDIAN_T_4 = Registry.register(BuiltInRegistries.BLOCK, new ResourceLocation(AioMod.MODID, "compressed_obsidian_t_4"), new CompressedObsidianT4Block());
		COMPRESSED_OBSIDIAN_T_5 = Registry.register(BuiltInRegistries.BLOCK, new ResourceLocation(AioMod.MODID, "compressed_obsidian_t_5"), new CompressedObsidianT5Block());
		NETHERRACK_T_1 = Registry.register(BuiltInRegistries.BLOCK, new ResourceLocation(AioMod.MODID, "netherrack_t_1"), new NetherrackT1Block());
		NETHERRACK_T_2 = Registry.register(BuiltInRegistries.BLOCK, new ResourceLocation(AioMod.MODID, "netherrack_t_2"), new NetherrackT2Block());
		NETHERRACK_T_3 = Registry.register(BuiltInRegistries.BLOCK, new ResourceLocation(AioMod.MODID, "netherrack_t_3"), new NetherrackT3Block());
		NETHERRACK_T_4 = Registry.register(BuiltInRegistries.BLOCK, new ResourceLocation(AioMod.MODID, "netherrack_t_4"), new NetherrackT4Block());
		NETHERRACK_T_5 = Registry.register(BuiltInRegistries.BLOCK, new ResourceLocation(AioMod.MODID, "netherrack_t_5"), new NetherrackT5Block());
		ENDSTONE_T_1 = Registry.register(BuiltInRegistries.BLOCK, new ResourceLocation(AioMod.MODID, "endstone_t_1"), new EndstoneT1Block());
		ENDSTONE_T_2 = Registry.register(BuiltInRegistries.BLOCK, new ResourceLocation(AioMod.MODID, "endstone_t_2"), new EndstoneT2Block());
		ENDSTONE_T_3 = Registry.register(BuiltInRegistries.BLOCK, new ResourceLocation(AioMod.MODID, "endstone_t_3"), new EndstoneT3Block());
		ENDSTONE_T_4 = Registry.register(BuiltInRegistries.BLOCK, new ResourceLocation(AioMod.MODID, "endstone_t_4"), new EndstoneT4Block());
		ENDSTONE_T_5 = Registry.register(BuiltInRegistries.BLOCK, new ResourceLocation(AioMod.MODID, "endstone_t_5"), new EndstoneT5Block());
		BASIC_LAMP = Registry.register(BuiltInRegistries.BLOCK, new ResourceLocation(AioMod.MODID, "basic_lamp"), new BasicLampBlock());
		LAUNCHER_MK_2 = Registry.register(BuiltInRegistries.BLOCK, new ResourceLocation(AioMod.MODID, "launcher_mk_2"), new LauncherMk2Block());
		LAUNCHER_MK_3 = Registry.register(BuiltInRegistries.BLOCK, new ResourceLocation(AioMod.MODID, "launcher_mk_3"), new LauncherMk3Block());
		LAUNCHER_MK_1 = Registry.register(BuiltInRegistries.BLOCK, new ResourceLocation(AioMod.MODID, "launcher_mk_1"), new LauncherMk1Block());
		EXPERIENCE_ALTAR = Registry.register(BuiltInRegistries.BLOCK, new ResourceLocation(AioMod.MODID, "experience_altar"), new ExperienceAltarBlock());
		COBBLE_GEN_MK_1 = Registry.register(BuiltInRegistries.BLOCK, new ResourceLocation(AioMod.MODID, "cobble_gen_mk_1"), new CobbleGenMk1Block());
	}

	public static void clientLoad() {
		TinOreBlock.clientInit();
		SilverOreBlock.clientInit();
		TinBlockBlock.clientInit();
		SilverBlockBlock.clientInit();
		SteelBlockBlock.clientInit();
		GlowBallBlockBlock.clientInit();
		MarbleBlock.clientInit();
		MarbleBricksBlock.clientInit();
		MarblePillarBlock.clientInit();
		CobbleT1Block.clientInit();
		CobbleT2Block.clientInit();
		CobbleT3Block.clientInit();
		CobbleT4Block.clientInit();
		CobbleT5Block.clientInit();
		StoneT1Block.clientInit();
		StoneT2Block.clientInit();
		StoneT3Block.clientInit();
		StoneT4Block.clientInit();
		StoneT5Block.clientInit();
		GravelT1Block.clientInit();
		GravelT2Block.clientInit();
		GravelT3Block.clientInit();
		GravelT4Block.clientInit();
		GravelT5Block.clientInit();
		DirtT1Block.clientInit();
		DirtT2Block.clientInit();
		DirtT3Block.clientInit();
		DirtT4Block.clientInit();
		DirtT5Block.clientInit();
		SandT1Block.clientInit();
		SandT2Block.clientInit();
		SandT3Block.clientInit();
		SandT4Block.clientInit();
		SandT5Block.clientInit();
		ClayT1Block.clientInit();
		ClayT2Block.clientInit();
		ClayT3Block.clientInit();
		ClayT4Block.clientInit();
		ClayT5Block.clientInit();
		CoalT1Block.clientInit();
		CoalT2Block.clientInit();
		CoalT3Block.clientInit();
		CoalT4Block.clientInit();
		CoalT5Block.clientInit();
		CompressedObsidianT1Block.clientInit();
		CompressedObsidianT2Block.clientInit();
		CompressedObsidianT3Block.clientInit();
		CompressedObsidianT4Block.clientInit();
		CompressedObsidianT5Block.clientInit();
		NetherrackT1Block.clientInit();
		NetherrackT2Block.clientInit();
		NetherrackT3Block.clientInit();
		NetherrackT4Block.clientInit();
		NetherrackT5Block.clientInit();
		EndstoneT1Block.clientInit();
		EndstoneT2Block.clientInit();
		EndstoneT3Block.clientInit();
		EndstoneT4Block.clientInit();
		EndstoneT5Block.clientInit();
		BasicLampBlock.clientInit();
		LauncherMk2Block.clientInit();
		LauncherMk3Block.clientInit();
		LauncherMk1Block.clientInit();
		ExperienceAltarBlock.clientInit();
		CobbleGenMk1Block.clientInit();
	}
}
