/*
 *	MCreator note: This file will be REGENERATED on each build.
 */
package net.lite.allinone.init;

import net.minecraft.world.item.Item;
import net.minecraft.world.item.BlockItem;
import net.minecraft.resources.ResourceLocation;
import net.minecraft.core.registries.BuiltInRegistries;
import net.minecraft.core.Registry;

import net.lite.allinone.item.TinSwordItem;
import net.lite.allinone.item.TinShovelItem;
import net.lite.allinone.item.TinPickaxeItem;
import net.lite.allinone.item.TinOreChunkItem;
import net.lite.allinone.item.TinIngotItem;
import net.lite.allinone.item.TinHoeItem;
import net.lite.allinone.item.TinDustItem;
import net.lite.allinone.item.TinAxeItem;
import net.lite.allinone.item.TinArmorItem;
import net.lite.allinone.item.StoneForgeHammerItem;
import net.lite.allinone.item.StoneDustItem;
import net.lite.allinone.item.SteelSwordItem;
import net.lite.allinone.item.SteelShovelItem;
import net.lite.allinone.item.SteelPickaxeItem;
import net.lite.allinone.item.SteelIngotItem;
import net.lite.allinone.item.SteelHoeItem;
import net.lite.allinone.item.SteelDustItem;
import net.lite.allinone.item.SteelAxeItem;
import net.lite.allinone.item.SteelArmorItem;
import net.lite.allinone.item.SilverSwordItem;
import net.lite.allinone.item.SilverShovelItem;
import net.lite.allinone.item.SilverPickaxeItem;
import net.lite.allinone.item.SilverOreChunkItem;
import net.lite.allinone.item.SilverIngotItem;
import net.lite.allinone.item.SilverHoeItem;
import net.lite.allinone.item.SilverDustItem;
import net.lite.allinone.item.SilverAxeItem;
import net.lite.allinone.item.SilverArmorItem;
import net.lite.allinone.item.PinkSlimeBallItem;
import net.lite.allinone.item.ObsidianSwordItem;
import net.lite.allinone.item.ObsidianShovelItem;
import net.lite.allinone.item.ObsidianPickaxeItem;
import net.lite.allinone.item.ObsidianHoeItem;
import net.lite.allinone.item.ObsidianForgeHammerItem;
import net.lite.allinone.item.ObsidianDustItem;
import net.lite.allinone.item.ObsidianAxeItem;
import net.lite.allinone.item.ObsidianArmorItem;
import net.lite.allinone.item.NetherStarFragmentItem;
import net.lite.allinone.item.NetherStarDustItem;
import net.lite.allinone.item.MouldingClayItem;
import net.lite.allinone.item.MarbleDustItem;
import net.lite.allinone.item.MagmaBrickItem;
import net.lite.allinone.item.IronForgeHammerItem;
import net.lite.allinone.item.HammerHeadMouldItem;
import net.lite.allinone.item.GlowBallItem;
import net.lite.allinone.item.ExperienceCookieItem;
import net.lite.allinone.item.EmeraldicSwordItem;
import net.lite.allinone.item.EmeraldicShovelItem;
import net.lite.allinone.item.EmeraldicPickaxeItem;
import net.lite.allinone.item.EmeraldicHoeItem;
import net.lite.allinone.item.EmeraldicAxeItem;
import net.lite.allinone.item.EmeraldicArmorItem;
import net.lite.allinone.item.EmeraldDustItem;
import net.lite.allinone.item.DiamondForgeHammerItem;
import net.lite.allinone.item.CopperSwordItem;
import net.lite.allinone.item.CopperShovelItem;
import net.lite.allinone.item.CopperPickaxeItem;
import net.lite.allinone.item.CopperHoeItem;
import net.lite.allinone.item.CopperForgeHammerItem;
import net.lite.allinone.item.CopperDustItem;
import net.lite.allinone.item.CopperAxeItem;
import net.lite.allinone.item.CopperArmorItem;
import net.lite.allinone.item.CoalDustItem;
import net.lite.allinone.item.BrickMouldItem;
import net.lite.allinone.item.AlloyMouldItem;
import net.lite.allinone.AioMod;

import net.fabricmc.fabric.api.itemgroup.v1.ItemGroupEvents;

public class AioModItems {
	public static Item TIN_ORE_CHUNK;
	public static Item SILVER_ORE_CHUNK;
	public static Item TIN_ORE;
	public static Item SILVER_ORE;
	public static Item TIN_BLOCK;
	public static Item SILVER_BLOCK;
	public static Item STEEL_BLOCK;
	public static Item BRICK_MOULD;
	public static Item HAMMER_HEAD_MOULD;
	public static Item ALLOY_MOULD;
	public static Item IRON_FORGE_HAMMER;
	public static Item DIAMOND_FORGE_HAMMER;
	public static Item STONE_FORGE_HAMMER;
	public static Item COPPER_FORGE_HAMMER;
	public static Item OBSIDIAN_FORGE_HAMMER;
	public static Item PINK_SLIME_BALL;
	public static Item MOULDING_CLAY;
	public static Item NETHER_STAR_FRAGMENT;
	public static Item GLOW_BALL;
	public static Item GLOW_BALL_BLOCK;
	public static Item MAGMA_BRICK;
	public static Item SILVER_INGOT;
	public static Item TIN_INGOT;
	public static Item STEEL_INGOT;
	public static Item COAL_DUST;
	public static Item NETHER_STAR_DUST;
	public static Item COPPER_DUST;
	public static Item STONE_DUST;
	public static Item TIN_DUST;
	public static Item SILVER_DUST;
	public static Item STEEL_DUST;
	public static Item EMERALD_DUST;
	public static Item OBSIDIAN_DUST;
	public static Item MARBLE;
	public static Item MARBLE_BRICKS;
	public static Item MARBLE_PILLAR;
	public static Item COBBLE_T_1;
	public static Item COBBLE_T_2;
	public static Item COBBLE_T_3;
	public static Item COBBLE_T_4;
	public static Item COBBLE_T_5;
	public static Item STONE_T_1;
	public static Item STONE_T_2;
	public static Item STONE_T_3;
	public static Item STONE_T_4;
	public static Item STONE_T_5;
	public static Item GRAVEL_T_1;
	public static Item GRAVEL_T_2;
	public static Item GRAVEL_T_3;
	public static Item GRAVEL_T_4;
	public static Item GRAVEL_T_5;
	public static Item DIRT_T_1;
	public static Item DIRT_T_2;
	public static Item DIRT_T_3;
	public static Item DIRT_T_4;
	public static Item DIRT_T_5;
	public static Item SAND_T_1;
	public static Item SAND_T_2;
	public static Item SAND_T_3;
	public static Item SAND_T_4;
	public static Item SAND_T_5;
	public static Item CLAY_T_1;
	public static Item CLAY_T_2;
	public static Item CLAY_T_3;
	public static Item CLAY_T_4;
	public static Item CLAY_T_5;
	public static Item COAL_T_1;
	public static Item COAL_T_2;
	public static Item COAL_T_3;
	public static Item COAL_T_4;
	public static Item COAL_T_5;
	public static Item COMPRESSED_OBSIDIAN_T_1;
	public static Item COMPRESSED_OBSIDIAN_T_2;
	public static Item COMPRESSED_OBSIDIAN_T_3;
	public static Item COMPRESSED_OBSIDIAN_T_4;
	public static Item COMPRESSED_OBSIDIAN_T_5;
	public static Item NETHERRACK_T_1;
	public static Item NETHERRACK_T_2;
	public static Item NETHERRACK_T_3;
	public static Item NETHERRACK_T_4;
	public static Item NETHERRACK_T_5;
	public static Item ENDSTONE_T_1;
	public static Item ENDSTONE_T_2;
	public static Item ENDSTONE_T_3;
	public static Item ENDSTONE_T_4;
	public static Item ENDSTONE_T_5;
	public static Item BASIC_LAMP;
	public static Item TIN_ARMOR_HELMET;
	public static Item TIN_ARMOR_CHESTPLATE;
	public static Item TIN_ARMOR_LEGGINGS;
	public static Item TIN_ARMOR_BOOTS;
	public static Item TIN_SWORD;
	public static Item COPPER_ARMOR_HELMET;
	public static Item COPPER_ARMOR_CHESTPLATE;
	public static Item COPPER_ARMOR_LEGGINGS;
	public static Item COPPER_ARMOR_BOOTS;
	public static Item COPPER_SWORD;
	public static Item SILVER_ARMOR_HELMET;
	public static Item SILVER_ARMOR_CHESTPLATE;
	public static Item SILVER_ARMOR_LEGGINGS;
	public static Item SILVER_ARMOR_BOOTS;
	public static Item SILVER_SWORD;
	public static Item STEEL_ARMOR_HELMET;
	public static Item STEEL_ARMOR_CHESTPLATE;
	public static Item STEEL_ARMOR_LEGGINGS;
	public static Item STEEL_ARMOR_BOOTS;
	public static Item STEEL_SWORD;
	public static Item EMERALDIC_ARMOR_HELMET;
	public static Item EMERALDIC_ARMOR_CHESTPLATE;
	public static Item EMERALDIC_ARMOR_LEGGINGS;
	public static Item EMERALDIC_ARMOR_BOOTS;
	public static Item EMERALDIC_SWORD;
	public static Item OBSIDIAN_ARMOR_HELMET;
	public static Item OBSIDIAN_ARMOR_CHESTPLATE;
	public static Item OBSIDIAN_ARMOR_LEGGINGS;
	public static Item OBSIDIAN_ARMOR_BOOTS;
	public static Item OBSIDIAN_SWORD;
	public static Item TIN_AXE;
	public static Item TIN_PICKAXE;
	public static Item TIN_SHOVEL;
	public static Item TIN_HOE;
	public static Item COPPER_PICKAXE;
	public static Item COPPER_AXE;
	public static Item COPPER_SHOVEL;
	public static Item COPPER_HOE;
	public static Item SILVER_PICKAXE;
	public static Item SILVER_AXE;
	public static Item SILVER_SHOVEL;
	public static Item SILVER_HOE;
	public static Item STEEL_PICKAXE;
	public static Item STEEL_AXE;
	public static Item STEEL_SHOVEL;
	public static Item STEEL_HOE;
	public static Item EMERALDIC_PICKAXE;
	public static Item EMERALDIC_AXE;
	public static Item EMERALDIC_SHOVEL;
	public static Item EMERALDIC_HOE;
	public static Item OBSIDIAN_PICKAXE;
	public static Item OBSIDIAN_AXE;
	public static Item OBSIDIAN_SHOVEL;
	public static Item OBSIDIAN_HOE;
	public static Item LAUNCHER_MK_2;
	public static Item LAUNCHER_MK_3;
	public static Item LAUNCHER_MK_1;
	public static Item EXPERIENCE_ALTAR;
	public static Item EXPERIENCE_COOKIE;
	public static Item COBBLE_GEN_MK_1;
	public static Item MARBLE_DUST;

	public static void load() {
		TIN_ORE_CHUNK = Registry.register(BuiltInRegistries.ITEM, new ResourceLocation(AioMod.MODID, "tin_ore_chunk"), new TinOreChunkItem());
		SILVER_ORE_CHUNK = Registry.register(BuiltInRegistries.ITEM, new ResourceLocation(AioMod.MODID, "silver_ore_chunk"), new SilverOreChunkItem());
		TIN_ORE = Registry.register(BuiltInRegistries.ITEM, new ResourceLocation(AioMod.MODID, "tin_ore"), new BlockItem(AioModBlocks.TIN_ORE, new Item.Properties()));
		ItemGroupEvents.modifyEntriesEvent(AioModTabs.TAB_ALL_IN_ONE).register(content -> content.accept(TIN_ORE));
		SILVER_ORE = Registry.register(BuiltInRegistries.ITEM, new ResourceLocation(AioMod.MODID, "silver_ore"), new BlockItem(AioModBlocks.SILVER_ORE, new Item.Properties()));
		ItemGroupEvents.modifyEntriesEvent(AioModTabs.TAB_ALL_IN_ONE).register(content -> content.accept(SILVER_ORE));
		TIN_BLOCK = Registry.register(BuiltInRegistries.ITEM, new ResourceLocation(AioMod.MODID, "tin_block"), new BlockItem(AioModBlocks.TIN_BLOCK, new Item.Properties()));
		ItemGroupEvents.modifyEntriesEvent(AioModTabs.TAB_ALL_IN_ONE).register(content -> content.accept(TIN_BLOCK));
		SILVER_BLOCK = Registry.register(BuiltInRegistries.ITEM, new ResourceLocation(AioMod.MODID, "silver_block"), new BlockItem(AioModBlocks.SILVER_BLOCK, new Item.Properties()));
		ItemGroupEvents.modifyEntriesEvent(AioModTabs.TAB_ALL_IN_ONE).register(content -> content.accept(SILVER_BLOCK));
		STEEL_BLOCK = Registry.register(BuiltInRegistries.ITEM, new ResourceLocation(AioMod.MODID, "steel_block"), new BlockItem(AioModBlocks.STEEL_BLOCK, new Item.Properties()));
		ItemGroupEvents.modifyEntriesEvent(AioModTabs.TAB_ALL_IN_ONE).register(content -> content.accept(STEEL_BLOCK));
		BRICK_MOULD = Registry.register(BuiltInRegistries.ITEM, new ResourceLocation(AioMod.MODID, "brick_mould"), new BrickMouldItem());
		HAMMER_HEAD_MOULD = Registry.register(BuiltInRegistries.ITEM, new ResourceLocation(AioMod.MODID, "hammer_head_mould"), new HammerHeadMouldItem());
		ALLOY_MOULD = Registry.register(BuiltInRegistries.ITEM, new ResourceLocation(AioMod.MODID, "alloy_mould"), new AlloyMouldItem());
		IRON_FORGE_HAMMER = Registry.register(BuiltInRegistries.ITEM, new ResourceLocation(AioMod.MODID, "iron_forge_hammer"), new IronForgeHammerItem());
		DIAMOND_FORGE_HAMMER = Registry.register(BuiltInRegistries.ITEM, new ResourceLocation(AioMod.MODID, "diamond_forge_hammer"), new DiamondForgeHammerItem());
		STONE_FORGE_HAMMER = Registry.register(BuiltInRegistries.ITEM, new ResourceLocation(AioMod.MODID, "stone_forge_hammer"), new StoneForgeHammerItem());
		COPPER_FORGE_HAMMER = Registry.register(BuiltInRegistries.ITEM, new ResourceLocation(AioMod.MODID, "copper_forge_hammer"), new CopperForgeHammerItem());
		OBSIDIAN_FORGE_HAMMER = Registry.register(BuiltInRegistries.ITEM, new ResourceLocation(AioMod.MODID, "obsidian_forge_hammer"), new ObsidianForgeHammerItem());
		PINK_SLIME_BALL = Registry.register(BuiltInRegistries.ITEM, new ResourceLocation(AioMod.MODID, "pink_slime_ball"), new PinkSlimeBallItem());
		MOULDING_CLAY = Registry.register(BuiltInRegistries.ITEM, new ResourceLocation(AioMod.MODID, "moulding_clay"), new MouldingClayItem());
		NETHER_STAR_FRAGMENT = Registry.register(BuiltInRegistries.ITEM, new ResourceLocation(AioMod.MODID, "nether_star_fragment"), new NetherStarFragmentItem());
		GLOW_BALL = Registry.register(BuiltInRegistries.ITEM, new ResourceLocation(AioMod.MODID, "glow_ball"), new GlowBallItem());
		GLOW_BALL_BLOCK = Registry.register(BuiltInRegistries.ITEM, new ResourceLocation(AioMod.MODID, "glow_ball_block"), new BlockItem(AioModBlocks.GLOW_BALL_BLOCK, new Item.Properties()));
		ItemGroupEvents.modifyEntriesEvent(AioModTabs.TAB_ALL_IN_ONE).register(content -> content.accept(GLOW_BALL_BLOCK));
		MAGMA_BRICK = Registry.register(BuiltInRegistries.ITEM, new ResourceLocation(AioMod.MODID, "magma_brick"), new MagmaBrickItem());
		SILVER_INGOT = Registry.register(BuiltInRegistries.ITEM, new ResourceLocation(AioMod.MODID, "silver_ingot"), new SilverIngotItem());
		TIN_INGOT = Registry.register(BuiltInRegistries.ITEM, new ResourceLocation(AioMod.MODID, "tin_ingot"), new TinIngotItem());
		STEEL_INGOT = Registry.register(BuiltInRegistries.ITEM, new ResourceLocation(AioMod.MODID, "steel_ingot"), new SteelIngotItem());
		COAL_DUST = Registry.register(BuiltInRegistries.ITEM, new ResourceLocation(AioMod.MODID, "coal_dust"), new CoalDustItem());
		NETHER_STAR_DUST = Registry.register(BuiltInRegistries.ITEM, new ResourceLocation(AioMod.MODID, "nether_star_dust"), new NetherStarDustItem());
		COPPER_DUST = Registry.register(BuiltInRegistries.ITEM, new ResourceLocation(AioMod.MODID, "copper_dust"), new CopperDustItem());
		STONE_DUST = Registry.register(BuiltInRegistries.ITEM, new ResourceLocation(AioMod.MODID, "stone_dust"), new StoneDustItem());
		TIN_DUST = Registry.register(BuiltInRegistries.ITEM, new ResourceLocation(AioMod.MODID, "tin_dust"), new TinDustItem());
		SILVER_DUST = Registry.register(BuiltInRegistries.ITEM, new ResourceLocation(AioMod.MODID, "silver_dust"), new SilverDustItem());
		STEEL_DUST = Registry.register(BuiltInRegistries.ITEM, new ResourceLocation(AioMod.MODID, "steel_dust"), new SteelDustItem());
		EMERALD_DUST = Registry.register(BuiltInRegistries.ITEM, new ResourceLocation(AioMod.MODID, "emerald_dust"), new EmeraldDustItem());
		OBSIDIAN_DUST = Registry.register(BuiltInRegistries.ITEM, new ResourceLocation(AioMod.MODID, "obsidian_dust"), new ObsidianDustItem());
		MARBLE = Registry.register(BuiltInRegistries.ITEM, new ResourceLocation(AioMod.MODID, "marble"), new BlockItem(AioModBlocks.MARBLE, new Item.Properties()));
		ItemGroupEvents.modifyEntriesEvent(AioModTabs.TAB_ALL_IN_ONE).register(content -> content.accept(MARBLE));
		MARBLE_BRICKS = Registry.register(BuiltInRegistries.ITEM, new ResourceLocation(AioMod.MODID, "marble_bricks"), new BlockItem(AioModBlocks.MARBLE_BRICKS, new Item.Properties()));
		ItemGroupEvents.modifyEntriesEvent(AioModTabs.TAB_ALL_IN_ONE).register(content -> content.accept(MARBLE_BRICKS));
		MARBLE_PILLAR = Registry.register(BuiltInRegistries.ITEM, new ResourceLocation(AioMod.MODID, "marble_pillar"), new BlockItem(AioModBlocks.MARBLE_PILLAR, new Item.Properties()));
		ItemGroupEvents.modifyEntriesEvent(AioModTabs.TAB_ALL_IN_ONE).register(content -> content.accept(MARBLE_PILLAR));
		COBBLE_T_1 = Registry.register(BuiltInRegistries.ITEM, new ResourceLocation(AioMod.MODID, "cobble_t_1"), new BlockItem(AioModBlocks.COBBLE_T_1, new Item.Properties()));
		ItemGroupEvents.modifyEntriesEvent(AioModTabs.TAB_ALL_IN_ONE).register(content -> content.accept(COBBLE_T_1));
		COBBLE_T_2 = Registry.register(BuiltInRegistries.ITEM, new ResourceLocation(AioMod.MODID, "cobble_t_2"), new BlockItem(AioModBlocks.COBBLE_T_2, new Item.Properties()));
		ItemGroupEvents.modifyEntriesEvent(AioModTabs.TAB_ALL_IN_ONE).register(content -> content.accept(COBBLE_T_2));
		COBBLE_T_3 = Registry.register(BuiltInRegistries.ITEM, new ResourceLocation(AioMod.MODID, "cobble_t_3"), new BlockItem(AioModBlocks.COBBLE_T_3, new Item.Properties()));
		ItemGroupEvents.modifyEntriesEvent(AioModTabs.TAB_ALL_IN_ONE).register(content -> content.accept(COBBLE_T_3));
		COBBLE_T_4 = Registry.register(BuiltInRegistries.ITEM, new ResourceLocation(AioMod.MODID, "cobble_t_4"), new BlockItem(AioModBlocks.COBBLE_T_4, new Item.Properties()));
		ItemGroupEvents.modifyEntriesEvent(AioModTabs.TAB_ALL_IN_ONE).register(content -> content.accept(COBBLE_T_4));
		COBBLE_T_5 = Registry.register(BuiltInRegistries.ITEM, new ResourceLocation(AioMod.MODID, "cobble_t_5"), new BlockItem(AioModBlocks.COBBLE_T_5, new Item.Properties()));
		ItemGroupEvents.modifyEntriesEvent(AioModTabs.TAB_ALL_IN_ONE).register(content -> content.accept(COBBLE_T_5));
		STONE_T_1 = Registry.register(BuiltInRegistries.ITEM, new ResourceLocation(AioMod.MODID, "stone_t_1"), new BlockItem(AioModBlocks.STONE_T_1, new Item.Properties()));
		ItemGroupEvents.modifyEntriesEvent(AioModTabs.TAB_ALL_IN_ONE).register(content -> content.accept(STONE_T_1));
		STONE_T_2 = Registry.register(BuiltInRegistries.ITEM, new ResourceLocation(AioMod.MODID, "stone_t_2"), new BlockItem(AioModBlocks.STONE_T_2, new Item.Properties()));
		ItemGroupEvents.modifyEntriesEvent(AioModTabs.TAB_ALL_IN_ONE).register(content -> content.accept(STONE_T_2));
		STONE_T_3 = Registry.register(BuiltInRegistries.ITEM, new ResourceLocation(AioMod.MODID, "stone_t_3"), new BlockItem(AioModBlocks.STONE_T_3, new Item.Properties()));
		ItemGroupEvents.modifyEntriesEvent(AioModTabs.TAB_ALL_IN_ONE).register(content -> content.accept(STONE_T_3));
		STONE_T_4 = Registry.register(BuiltInRegistries.ITEM, new ResourceLocation(AioMod.MODID, "stone_t_4"), new BlockItem(AioModBlocks.STONE_T_4, new Item.Properties()));
		ItemGroupEvents.modifyEntriesEvent(AioModTabs.TAB_ALL_IN_ONE).register(content -> content.accept(STONE_T_4));
		STONE_T_5 = Registry.register(BuiltInRegistries.ITEM, new ResourceLocation(AioMod.MODID, "stone_t_5"), new BlockItem(AioModBlocks.STONE_T_5, new Item.Properties()));
		ItemGroupEvents.modifyEntriesEvent(AioModTabs.TAB_ALL_IN_ONE).register(content -> content.accept(STONE_T_5));
		GRAVEL_T_1 = Registry.register(BuiltInRegistries.ITEM, new ResourceLocation(AioMod.MODID, "gravel_t_1"), new BlockItem(AioModBlocks.GRAVEL_T_1, new Item.Properties()));
		ItemGroupEvents.modifyEntriesEvent(AioModTabs.TAB_ALL_IN_ONE).register(content -> content.accept(GRAVEL_T_1));
		GRAVEL_T_2 = Registry.register(BuiltInRegistries.ITEM, new ResourceLocation(AioMod.MODID, "gravel_t_2"), new BlockItem(AioModBlocks.GRAVEL_T_2, new Item.Properties()));
		ItemGroupEvents.modifyEntriesEvent(AioModTabs.TAB_ALL_IN_ONE).register(content -> content.accept(GRAVEL_T_2));
		GRAVEL_T_3 = Registry.register(BuiltInRegistries.ITEM, new ResourceLocation(AioMod.MODID, "gravel_t_3"), new BlockItem(AioModBlocks.GRAVEL_T_3, new Item.Properties()));
		ItemGroupEvents.modifyEntriesEvent(AioModTabs.TAB_ALL_IN_ONE).register(content -> content.accept(GRAVEL_T_3));
		GRAVEL_T_4 = Registry.register(BuiltInRegistries.ITEM, new ResourceLocation(AioMod.MODID, "gravel_t_4"), new BlockItem(AioModBlocks.GRAVEL_T_4, new Item.Properties()));
		ItemGroupEvents.modifyEntriesEvent(AioModTabs.TAB_ALL_IN_ONE).register(content -> content.accept(GRAVEL_T_4));
		GRAVEL_T_5 = Registry.register(BuiltInRegistries.ITEM, new ResourceLocation(AioMod.MODID, "gravel_t_5"), new BlockItem(AioModBlocks.GRAVEL_T_5, new Item.Properties()));
		ItemGroupEvents.modifyEntriesEvent(AioModTabs.TAB_ALL_IN_ONE).register(content -> content.accept(GRAVEL_T_5));
		DIRT_T_1 = Registry.register(BuiltInRegistries.ITEM, new ResourceLocation(AioMod.MODID, "dirt_t_1"), new BlockItem(AioModBlocks.DIRT_T_1, new Item.Properties()));
		ItemGroupEvents.modifyEntriesEvent(AioModTabs.TAB_ALL_IN_ONE).register(content -> content.accept(DIRT_T_1));
		DIRT_T_2 = Registry.register(BuiltInRegistries.ITEM, new ResourceLocation(AioMod.MODID, "dirt_t_2"), new BlockItem(AioModBlocks.DIRT_T_2, new Item.Properties()));
		ItemGroupEvents.modifyEntriesEvent(AioModTabs.TAB_ALL_IN_ONE).register(content -> content.accept(DIRT_T_2));
		DIRT_T_3 = Registry.register(BuiltInRegistries.ITEM, new ResourceLocation(AioMod.MODID, "dirt_t_3"), new BlockItem(AioModBlocks.DIRT_T_3, new Item.Properties()));
		ItemGroupEvents.modifyEntriesEvent(AioModTabs.TAB_ALL_IN_ONE).register(content -> content.accept(DIRT_T_3));
		DIRT_T_4 = Registry.register(BuiltInRegistries.ITEM, new ResourceLocation(AioMod.MODID, "dirt_t_4"), new BlockItem(AioModBlocks.DIRT_T_4, new Item.Properties()));
		ItemGroupEvents.modifyEntriesEvent(AioModTabs.TAB_ALL_IN_ONE).register(content -> content.accept(DIRT_T_4));
		DIRT_T_5 = Registry.register(BuiltInRegistries.ITEM, new ResourceLocation(AioMod.MODID, "dirt_t_5"), new BlockItem(AioModBlocks.DIRT_T_5, new Item.Properties()));
		ItemGroupEvents.modifyEntriesEvent(AioModTabs.TAB_ALL_IN_ONE).register(content -> content.accept(DIRT_T_5));
		SAND_T_1 = Registry.register(BuiltInRegistries.ITEM, new ResourceLocation(AioMod.MODID, "sand_t_1"), new BlockItem(AioModBlocks.SAND_T_1, new Item.Properties()));
		ItemGroupEvents.modifyEntriesEvent(AioModTabs.TAB_ALL_IN_ONE).register(content -> content.accept(SAND_T_1));
		SAND_T_2 = Registry.register(BuiltInRegistries.ITEM, new ResourceLocation(AioMod.MODID, "sand_t_2"), new BlockItem(AioModBlocks.SAND_T_2, new Item.Properties()));
		ItemGroupEvents.modifyEntriesEvent(AioModTabs.TAB_ALL_IN_ONE).register(content -> content.accept(SAND_T_2));
		SAND_T_3 = Registry.register(BuiltInRegistries.ITEM, new ResourceLocation(AioMod.MODID, "sand_t_3"), new BlockItem(AioModBlocks.SAND_T_3, new Item.Properties()));
		ItemGroupEvents.modifyEntriesEvent(AioModTabs.TAB_ALL_IN_ONE).register(content -> content.accept(SAND_T_3));
		SAND_T_4 = Registry.register(BuiltInRegistries.ITEM, new ResourceLocation(AioMod.MODID, "sand_t_4"), new BlockItem(AioModBlocks.SAND_T_4, new Item.Properties()));
		ItemGroupEvents.modifyEntriesEvent(AioModTabs.TAB_ALL_IN_ONE).register(content -> content.accept(SAND_T_4));
		SAND_T_5 = Registry.register(BuiltInRegistries.ITEM, new ResourceLocation(AioMod.MODID, "sand_t_5"), new BlockItem(AioModBlocks.SAND_T_5, new Item.Properties()));
		ItemGroupEvents.modifyEntriesEvent(AioModTabs.TAB_ALL_IN_ONE).register(content -> content.accept(SAND_T_5));
		CLAY_T_1 = Registry.register(BuiltInRegistries.ITEM, new ResourceLocation(AioMod.MODID, "clay_t_1"), new BlockItem(AioModBlocks.CLAY_T_1, new Item.Properties()));
		ItemGroupEvents.modifyEntriesEvent(AioModTabs.TAB_ALL_IN_ONE).register(content -> content.accept(CLAY_T_1));
		CLAY_T_2 = Registry.register(BuiltInRegistries.ITEM, new ResourceLocation(AioMod.MODID, "clay_t_2"), new BlockItem(AioModBlocks.CLAY_T_2, new Item.Properties()));
		ItemGroupEvents.modifyEntriesEvent(AioModTabs.TAB_ALL_IN_ONE).register(content -> content.accept(CLAY_T_2));
		CLAY_T_3 = Registry.register(BuiltInRegistries.ITEM, new ResourceLocation(AioMod.MODID, "clay_t_3"), new BlockItem(AioModBlocks.CLAY_T_3, new Item.Properties()));
		ItemGroupEvents.modifyEntriesEvent(AioModTabs.TAB_ALL_IN_ONE).register(content -> content.accept(CLAY_T_3));
		CLAY_T_4 = Registry.register(BuiltInRegistries.ITEM, new ResourceLocation(AioMod.MODID, "clay_t_4"), new BlockItem(AioModBlocks.CLAY_T_4, new Item.Properties()));
		ItemGroupEvents.modifyEntriesEvent(AioModTabs.TAB_ALL_IN_ONE).register(content -> content.accept(CLAY_T_4));
		CLAY_T_5 = Registry.register(BuiltInRegistries.ITEM, new ResourceLocation(AioMod.MODID, "clay_t_5"), new BlockItem(AioModBlocks.CLAY_T_5, new Item.Properties()));
		ItemGroupEvents.modifyEntriesEvent(AioModTabs.TAB_ALL_IN_ONE).register(content -> content.accept(CLAY_T_5));
		COAL_T_1 = Registry.register(BuiltInRegistries.ITEM, new ResourceLocation(AioMod.MODID, "coal_t_1"), new BlockItem(AioModBlocks.COAL_T_1, new Item.Properties()));
		ItemGroupEvents.modifyEntriesEvent(AioModTabs.TAB_ALL_IN_ONE).register(content -> content.accept(COAL_T_1));
		COAL_T_2 = Registry.register(BuiltInRegistries.ITEM, new ResourceLocation(AioMod.MODID, "coal_t_2"), new BlockItem(AioModBlocks.COAL_T_2, new Item.Properties()));
		ItemGroupEvents.modifyEntriesEvent(AioModTabs.TAB_ALL_IN_ONE).register(content -> content.accept(COAL_T_2));
		COAL_T_3 = Registry.register(BuiltInRegistries.ITEM, new ResourceLocation(AioMod.MODID, "coal_t_3"), new BlockItem(AioModBlocks.COAL_T_3, new Item.Properties()));
		ItemGroupEvents.modifyEntriesEvent(AioModTabs.TAB_ALL_IN_ONE).register(content -> content.accept(COAL_T_3));
		COAL_T_4 = Registry.register(BuiltInRegistries.ITEM, new ResourceLocation(AioMod.MODID, "coal_t_4"), new BlockItem(AioModBlocks.COAL_T_4, new Item.Properties()));
		ItemGroupEvents.modifyEntriesEvent(AioModTabs.TAB_ALL_IN_ONE).register(content -> content.accept(COAL_T_4));
		COAL_T_5 = Registry.register(BuiltInRegistries.ITEM, new ResourceLocation(AioMod.MODID, "coal_t_5"), new BlockItem(AioModBlocks.COAL_T_5, new Item.Properties()));
		ItemGroupEvents.modifyEntriesEvent(AioModTabs.TAB_ALL_IN_ONE).register(content -> content.accept(COAL_T_5));
		COMPRESSED_OBSIDIAN_T_1 = Registry.register(BuiltInRegistries.ITEM, new ResourceLocation(AioMod.MODID, "compressed_obsidian_t_1"), new BlockItem(AioModBlocks.COMPRESSED_OBSIDIAN_T_1, new Item.Properties()));
		ItemGroupEvents.modifyEntriesEvent(AioModTabs.TAB_ALL_IN_ONE).register(content -> content.accept(COMPRESSED_OBSIDIAN_T_1));
		COMPRESSED_OBSIDIAN_T_2 = Registry.register(BuiltInRegistries.ITEM, new ResourceLocation(AioMod.MODID, "compressed_obsidian_t_2"), new BlockItem(AioModBlocks.COMPRESSED_OBSIDIAN_T_2, new Item.Properties()));
		ItemGroupEvents.modifyEntriesEvent(AioModTabs.TAB_ALL_IN_ONE).register(content -> content.accept(COMPRESSED_OBSIDIAN_T_2));
		COMPRESSED_OBSIDIAN_T_3 = Registry.register(BuiltInRegistries.ITEM, new ResourceLocation(AioMod.MODID, "compressed_obsidian_t_3"), new BlockItem(AioModBlocks.COMPRESSED_OBSIDIAN_T_3, new Item.Properties()));
		ItemGroupEvents.modifyEntriesEvent(AioModTabs.TAB_ALL_IN_ONE).register(content -> content.accept(COMPRESSED_OBSIDIAN_T_3));
		COMPRESSED_OBSIDIAN_T_4 = Registry.register(BuiltInRegistries.ITEM, new ResourceLocation(AioMod.MODID, "compressed_obsidian_t_4"), new BlockItem(AioModBlocks.COMPRESSED_OBSIDIAN_T_4, new Item.Properties()));
		ItemGroupEvents.modifyEntriesEvent(AioModTabs.TAB_ALL_IN_ONE).register(content -> content.accept(COMPRESSED_OBSIDIAN_T_4));
		COMPRESSED_OBSIDIAN_T_5 = Registry.register(BuiltInRegistries.ITEM, new ResourceLocation(AioMod.MODID, "compressed_obsidian_t_5"), new BlockItem(AioModBlocks.COMPRESSED_OBSIDIAN_T_5, new Item.Properties()));
		ItemGroupEvents.modifyEntriesEvent(AioModTabs.TAB_ALL_IN_ONE).register(content -> content.accept(COMPRESSED_OBSIDIAN_T_5));
		NETHERRACK_T_1 = Registry.register(BuiltInRegistries.ITEM, new ResourceLocation(AioMod.MODID, "netherrack_t_1"), new BlockItem(AioModBlocks.NETHERRACK_T_1, new Item.Properties()));
		ItemGroupEvents.modifyEntriesEvent(AioModTabs.TAB_ALL_IN_ONE).register(content -> content.accept(NETHERRACK_T_1));
		NETHERRACK_T_2 = Registry.register(BuiltInRegistries.ITEM, new ResourceLocation(AioMod.MODID, "netherrack_t_2"), new BlockItem(AioModBlocks.NETHERRACK_T_2, new Item.Properties()));
		ItemGroupEvents.modifyEntriesEvent(AioModTabs.TAB_ALL_IN_ONE).register(content -> content.accept(NETHERRACK_T_2));
		NETHERRACK_T_3 = Registry.register(BuiltInRegistries.ITEM, new ResourceLocation(AioMod.MODID, "netherrack_t_3"), new BlockItem(AioModBlocks.NETHERRACK_T_3, new Item.Properties()));
		ItemGroupEvents.modifyEntriesEvent(AioModTabs.TAB_ALL_IN_ONE).register(content -> content.accept(NETHERRACK_T_3));
		NETHERRACK_T_4 = Registry.register(BuiltInRegistries.ITEM, new ResourceLocation(AioMod.MODID, "netherrack_t_4"), new BlockItem(AioModBlocks.NETHERRACK_T_4, new Item.Properties()));
		ItemGroupEvents.modifyEntriesEvent(AioModTabs.TAB_ALL_IN_ONE).register(content -> content.accept(NETHERRACK_T_4));
		NETHERRACK_T_5 = Registry.register(BuiltInRegistries.ITEM, new ResourceLocation(AioMod.MODID, "netherrack_t_5"), new BlockItem(AioModBlocks.NETHERRACK_T_5, new Item.Properties()));
		ItemGroupEvents.modifyEntriesEvent(AioModTabs.TAB_ALL_IN_ONE).register(content -> content.accept(NETHERRACK_T_5));
		ENDSTONE_T_1 = Registry.register(BuiltInRegistries.ITEM, new ResourceLocation(AioMod.MODID, "endstone_t_1"), new BlockItem(AioModBlocks.ENDSTONE_T_1, new Item.Properties()));
		ItemGroupEvents.modifyEntriesEvent(AioModTabs.TAB_ALL_IN_ONE).register(content -> content.accept(ENDSTONE_T_1));
		ENDSTONE_T_2 = Registry.register(BuiltInRegistries.ITEM, new ResourceLocation(AioMod.MODID, "endstone_t_2"), new BlockItem(AioModBlocks.ENDSTONE_T_2, new Item.Properties()));
		ItemGroupEvents.modifyEntriesEvent(AioModTabs.TAB_ALL_IN_ONE).register(content -> content.accept(ENDSTONE_T_2));
		ENDSTONE_T_3 = Registry.register(BuiltInRegistries.ITEM, new ResourceLocation(AioMod.MODID, "endstone_t_3"), new BlockItem(AioModBlocks.ENDSTONE_T_3, new Item.Properties()));
		ItemGroupEvents.modifyEntriesEvent(AioModTabs.TAB_ALL_IN_ONE).register(content -> content.accept(ENDSTONE_T_3));
		ENDSTONE_T_4 = Registry.register(BuiltInRegistries.ITEM, new ResourceLocation(AioMod.MODID, "endstone_t_4"), new BlockItem(AioModBlocks.ENDSTONE_T_4, new Item.Properties()));
		ItemGroupEvents.modifyEntriesEvent(AioModTabs.TAB_ALL_IN_ONE).register(content -> content.accept(ENDSTONE_T_4));
		ENDSTONE_T_5 = Registry.register(BuiltInRegistries.ITEM, new ResourceLocation(AioMod.MODID, "endstone_t_5"), new BlockItem(AioModBlocks.ENDSTONE_T_5, new Item.Properties()));
		ItemGroupEvents.modifyEntriesEvent(AioModTabs.TAB_ALL_IN_ONE).register(content -> content.accept(ENDSTONE_T_5));
		BASIC_LAMP = Registry.register(BuiltInRegistries.ITEM, new ResourceLocation(AioMod.MODID, "basic_lamp"), new BlockItem(AioModBlocks.BASIC_LAMP, new Item.Properties()));
		ItemGroupEvents.modifyEntriesEvent(AioModTabs.TAB_ALL_IN_ONE).register(content -> content.accept(BASIC_LAMP));
		TIN_ARMOR_HELMET = Registry.register(BuiltInRegistries.ITEM, new ResourceLocation(AioMod.MODID, "tin_armor_helmet"), new TinArmorItem.Helmet());
		TIN_ARMOR_CHESTPLATE = Registry.register(BuiltInRegistries.ITEM, new ResourceLocation(AioMod.MODID, "tin_armor_chestplate"), new TinArmorItem.Chestplate());
		TIN_ARMOR_LEGGINGS = Registry.register(BuiltInRegistries.ITEM, new ResourceLocation(AioMod.MODID, "tin_armor_leggings"), new TinArmorItem.Leggings());
		TIN_ARMOR_BOOTS = Registry.register(BuiltInRegistries.ITEM, new ResourceLocation(AioMod.MODID, "tin_armor_boots"), new TinArmorItem.Boots());
		TIN_SWORD = Registry.register(BuiltInRegistries.ITEM, new ResourceLocation(AioMod.MODID, "tin_sword"), new TinSwordItem());
		COPPER_ARMOR_HELMET = Registry.register(BuiltInRegistries.ITEM, new ResourceLocation(AioMod.MODID, "copper_armor_helmet"), new CopperArmorItem.Helmet());
		COPPER_ARMOR_CHESTPLATE = Registry.register(BuiltInRegistries.ITEM, new ResourceLocation(AioMod.MODID, "copper_armor_chestplate"), new CopperArmorItem.Chestplate());
		COPPER_ARMOR_LEGGINGS = Registry.register(BuiltInRegistries.ITEM, new ResourceLocation(AioMod.MODID, "copper_armor_leggings"), new CopperArmorItem.Leggings());
		COPPER_ARMOR_BOOTS = Registry.register(BuiltInRegistries.ITEM, new ResourceLocation(AioMod.MODID, "copper_armor_boots"), new CopperArmorItem.Boots());
		COPPER_SWORD = Registry.register(BuiltInRegistries.ITEM, new ResourceLocation(AioMod.MODID, "copper_sword"), new CopperSwordItem());
		SILVER_ARMOR_HELMET = Registry.register(BuiltInRegistries.ITEM, new ResourceLocation(AioMod.MODID, "silver_armor_helmet"), new SilverArmorItem.Helmet());
		SILVER_ARMOR_CHESTPLATE = Registry.register(BuiltInRegistries.ITEM, new ResourceLocation(AioMod.MODID, "silver_armor_chestplate"), new SilverArmorItem.Chestplate());
		SILVER_ARMOR_LEGGINGS = Registry.register(BuiltInRegistries.ITEM, new ResourceLocation(AioMod.MODID, "silver_armor_leggings"), new SilverArmorItem.Leggings());
		SILVER_ARMOR_BOOTS = Registry.register(BuiltInRegistries.ITEM, new ResourceLocation(AioMod.MODID, "silver_armor_boots"), new SilverArmorItem.Boots());
		SILVER_SWORD = Registry.register(BuiltInRegistries.ITEM, new ResourceLocation(AioMod.MODID, "silver_sword"), new SilverSwordItem());
		STEEL_ARMOR_HELMET = Registry.register(BuiltInRegistries.ITEM, new ResourceLocation(AioMod.MODID, "steel_armor_helmet"), new SteelArmorItem.Helmet());
		STEEL_ARMOR_CHESTPLATE = Registry.register(BuiltInRegistries.ITEM, new ResourceLocation(AioMod.MODID, "steel_armor_chestplate"), new SteelArmorItem.Chestplate());
		STEEL_ARMOR_LEGGINGS = Registry.register(BuiltInRegistries.ITEM, new ResourceLocation(AioMod.MODID, "steel_armor_leggings"), new SteelArmorItem.Leggings());
		STEEL_ARMOR_BOOTS = Registry.register(BuiltInRegistries.ITEM, new ResourceLocation(AioMod.MODID, "steel_armor_boots"), new SteelArmorItem.Boots());
		STEEL_SWORD = Registry.register(BuiltInRegistries.ITEM, new ResourceLocation(AioMod.MODID, "steel_sword"), new SteelSwordItem());
		EMERALDIC_ARMOR_HELMET = Registry.register(BuiltInRegistries.ITEM, new ResourceLocation(AioMod.MODID, "emeraldic_armor_helmet"), new EmeraldicArmorItem.Helmet());
		EMERALDIC_ARMOR_CHESTPLATE = Registry.register(BuiltInRegistries.ITEM, new ResourceLocation(AioMod.MODID, "emeraldic_armor_chestplate"), new EmeraldicArmorItem.Chestplate());
		EMERALDIC_ARMOR_LEGGINGS = Registry.register(BuiltInRegistries.ITEM, new ResourceLocation(AioMod.MODID, "emeraldic_armor_leggings"), new EmeraldicArmorItem.Leggings());
		EMERALDIC_ARMOR_BOOTS = Registry.register(BuiltInRegistries.ITEM, new ResourceLocation(AioMod.MODID, "emeraldic_armor_boots"), new EmeraldicArmorItem.Boots());
		EMERALDIC_SWORD = Registry.register(BuiltInRegistries.ITEM, new ResourceLocation(AioMod.MODID, "emeraldic_sword"), new EmeraldicSwordItem());
		OBSIDIAN_ARMOR_HELMET = Registry.register(BuiltInRegistries.ITEM, new ResourceLocation(AioMod.MODID, "obsidian_armor_helmet"), new ObsidianArmorItem.Helmet());
		OBSIDIAN_ARMOR_CHESTPLATE = Registry.register(BuiltInRegistries.ITEM, new ResourceLocation(AioMod.MODID, "obsidian_armor_chestplate"), new ObsidianArmorItem.Chestplate());
		OBSIDIAN_ARMOR_LEGGINGS = Registry.register(BuiltInRegistries.ITEM, new ResourceLocation(AioMod.MODID, "obsidian_armor_leggings"), new ObsidianArmorItem.Leggings());
		OBSIDIAN_ARMOR_BOOTS = Registry.register(BuiltInRegistries.ITEM, new ResourceLocation(AioMod.MODID, "obsidian_armor_boots"), new ObsidianArmorItem.Boots());
		OBSIDIAN_SWORD = Registry.register(BuiltInRegistries.ITEM, new ResourceLocation(AioMod.MODID, "obsidian_sword"), new ObsidianSwordItem());
		TIN_AXE = Registry.register(BuiltInRegistries.ITEM, new ResourceLocation(AioMod.MODID, "tin_axe"), new TinAxeItem());
		TIN_PICKAXE = Registry.register(BuiltInRegistries.ITEM, new ResourceLocation(AioMod.MODID, "tin_pickaxe"), new TinPickaxeItem());
		TIN_SHOVEL = Registry.register(BuiltInRegistries.ITEM, new ResourceLocation(AioMod.MODID, "tin_shovel"), new TinShovelItem());
		TIN_HOE = Registry.register(BuiltInRegistries.ITEM, new ResourceLocation(AioMod.MODID, "tin_hoe"), new TinHoeItem());
		COPPER_PICKAXE = Registry.register(BuiltInRegistries.ITEM, new ResourceLocation(AioMod.MODID, "copper_pickaxe"), new CopperPickaxeItem());
		COPPER_AXE = Registry.register(BuiltInRegistries.ITEM, new ResourceLocation(AioMod.MODID, "copper_axe"), new CopperAxeItem());
		COPPER_SHOVEL = Registry.register(BuiltInRegistries.ITEM, new ResourceLocation(AioMod.MODID, "copper_shovel"), new CopperShovelItem());
		COPPER_HOE = Registry.register(BuiltInRegistries.ITEM, new ResourceLocation(AioMod.MODID, "copper_hoe"), new CopperHoeItem());
		SILVER_PICKAXE = Registry.register(BuiltInRegistries.ITEM, new ResourceLocation(AioMod.MODID, "silver_pickaxe"), new SilverPickaxeItem());
		SILVER_AXE = Registry.register(BuiltInRegistries.ITEM, new ResourceLocation(AioMod.MODID, "silver_axe"), new SilverAxeItem());
		SILVER_SHOVEL = Registry.register(BuiltInRegistries.ITEM, new ResourceLocation(AioMod.MODID, "silver_shovel"), new SilverShovelItem());
		SILVER_HOE = Registry.register(BuiltInRegistries.ITEM, new ResourceLocation(AioMod.MODID, "silver_hoe"), new SilverHoeItem());
		STEEL_PICKAXE = Registry.register(BuiltInRegistries.ITEM, new ResourceLocation(AioMod.MODID, "steel_pickaxe"), new SteelPickaxeItem());
		STEEL_AXE = Registry.register(BuiltInRegistries.ITEM, new ResourceLocation(AioMod.MODID, "steel_axe"), new SteelAxeItem());
		STEEL_SHOVEL = Registry.register(BuiltInRegistries.ITEM, new ResourceLocation(AioMod.MODID, "steel_shovel"), new SteelShovelItem());
		STEEL_HOE = Registry.register(BuiltInRegistries.ITEM, new ResourceLocation(AioMod.MODID, "steel_hoe"), new SteelHoeItem());
		EMERALDIC_PICKAXE = Registry.register(BuiltInRegistries.ITEM, new ResourceLocation(AioMod.MODID, "emeraldic_pickaxe"), new EmeraldicPickaxeItem());
		EMERALDIC_AXE = Registry.register(BuiltInRegistries.ITEM, new ResourceLocation(AioMod.MODID, "emeraldic_axe"), new EmeraldicAxeItem());
		EMERALDIC_SHOVEL = Registry.register(BuiltInRegistries.ITEM, new ResourceLocation(AioMod.MODID, "emeraldic_shovel"), new EmeraldicShovelItem());
		EMERALDIC_HOE = Registry.register(BuiltInRegistries.ITEM, new ResourceLocation(AioMod.MODID, "emeraldic_hoe"), new EmeraldicHoeItem());
		OBSIDIAN_PICKAXE = Registry.register(BuiltInRegistries.ITEM, new ResourceLocation(AioMod.MODID, "obsidian_pickaxe"), new ObsidianPickaxeItem());
		OBSIDIAN_AXE = Registry.register(BuiltInRegistries.ITEM, new ResourceLocation(AioMod.MODID, "obsidian_axe"), new ObsidianAxeItem());
		OBSIDIAN_SHOVEL = Registry.register(BuiltInRegistries.ITEM, new ResourceLocation(AioMod.MODID, "obsidian_shovel"), new ObsidianShovelItem());
		OBSIDIAN_HOE = Registry.register(BuiltInRegistries.ITEM, new ResourceLocation(AioMod.MODID, "obsidian_hoe"), new ObsidianHoeItem());
		LAUNCHER_MK_2 = Registry.register(BuiltInRegistries.ITEM, new ResourceLocation(AioMod.MODID, "launcher_mk_2"), new BlockItem(AioModBlocks.LAUNCHER_MK_2, new Item.Properties()));
		ItemGroupEvents.modifyEntriesEvent(AioModTabs.TAB_ALL_IN_ONE).register(content -> content.accept(LAUNCHER_MK_2));
		LAUNCHER_MK_3 = Registry.register(BuiltInRegistries.ITEM, new ResourceLocation(AioMod.MODID, "launcher_mk_3"), new BlockItem(AioModBlocks.LAUNCHER_MK_3, new Item.Properties()));
		ItemGroupEvents.modifyEntriesEvent(AioModTabs.TAB_ALL_IN_ONE).register(content -> content.accept(LAUNCHER_MK_3));
		LAUNCHER_MK_1 = Registry.register(BuiltInRegistries.ITEM, new ResourceLocation(AioMod.MODID, "launcher_mk_1"), new BlockItem(AioModBlocks.LAUNCHER_MK_1, new Item.Properties()));
		ItemGroupEvents.modifyEntriesEvent(AioModTabs.TAB_ALL_IN_ONE).register(content -> content.accept(LAUNCHER_MK_1));
		EXPERIENCE_ALTAR = Registry.register(BuiltInRegistries.ITEM, new ResourceLocation(AioMod.MODID, "experience_altar"), new BlockItem(AioModBlocks.EXPERIENCE_ALTAR, new Item.Properties()));
		ItemGroupEvents.modifyEntriesEvent(AioModTabs.TAB_ALL_IN_ONE).register(content -> content.accept(EXPERIENCE_ALTAR));
		EXPERIENCE_COOKIE = Registry.register(BuiltInRegistries.ITEM, new ResourceLocation(AioMod.MODID, "experience_cookie"), new ExperienceCookieItem());
		COBBLE_GEN_MK_1 = Registry.register(BuiltInRegistries.ITEM, new ResourceLocation(AioMod.MODID, "cobble_gen_mk_1"), new BlockItem(AioModBlocks.COBBLE_GEN_MK_1, new Item.Properties()));
		ItemGroupEvents.modifyEntriesEvent(AioModTabs.TAB_ALL_IN_ONE).register(content -> content.accept(COBBLE_GEN_MK_1));
		MARBLE_DUST = Registry.register(BuiltInRegistries.ITEM, new ResourceLocation(AioMod.MODID, "marble_dust"), new MarbleDustItem());
	}

	public static void clientLoad() {
	}
}
